---
# base system packages for jenkins master and workers
- name: get software for apt repository management.
  apt:
    pkg:
      - python3-apt
      - python3-pycurl
    state: present

- name: install java11
  apt:
    pkg: openjdk-11-jdk
    state: present
    update_cache: yes
    force: yes

- name: install java8
  apt:
    pkg: openjdk-8-jdk
    state: present
    update_cache: yes
    force: yes

- name: make easy to remember dir for java symlinks
  file:
    path: /usr/java
    state: directory

- name: link java8 to /usr/java/latest
  file:
    src: /usr/lib/jvm/java-8-openjdk-amd64/
    dest: /usr/java/latest
    state: link

- name: link java8 to /usr/java/java8
  file:
    src: /usr/lib/jvm/java-8-openjdk-amd64/
    dest: /usr/java/java8
    state: link

- name: link java11 to /usr/java/java11
  file:
    src: /usr/lib/jvm/java-11-openjdk-amd64/
    dest: /usr/java/java11
    state: link

- name: set java8 as default
  alternatives:
    name: "{{ item.command }}"
    path: "{{ item.path }}"
  loop:
    - { command: 'java', path: '/usr/java/latest/bin/java' }
    - { command: 'javah', path: '/usr/java/latest/bin/javah' }
    - { command: 'javac', path: '/usr/java/latest/bin/javac' }
    - { command: 'jar', path: '/usr/java/latest/bin/jar' }

- name: install base system packages
  apt:
    pkg:
      - apt-transport-https
      - gnupg-agent
      - ipmitool
      - git
      - ntp
      - htop
      - tree
      - gzip
      - bzip2
      - curl
      - wget
      - unzip
    state: present
    update_cache: yes
