
###################################################
#
# Benchmark Configuration
#
# NOTE: `conf.tmpl.sh` contains all the variables
#   that will be used by all benchmarks. Set them
#   before starting benchmarking.
#
# NOTE: `conf.tmpl.sh` will be copied to `conf.sh`
#   along with the per-benchmark confguration.
#   Do not modify `conf.sh` as it will be
#   regenerated by `gen-conf.sh` script.
#
###################################################


# USER
LOGIN=$(whoami)

# Fixed variables
# ----------------------

# JAVA Home
JAVA_PATH="/home1/public/${LOGIN}/work/teraheap/jdk17/build/linux-x86_64-server-release/jdk"
# Repo to TeraHeap
TERAHEAP_REPO="/home1/public/${LOGIN}/work/teraheap"
# Benchmark repo
BENCH_DIR="/home1/public/${LOGIN}/tera_applications"
# Dataset
DATASET=/mnt/spark/indexOffHeap90GB
# Device for dataset
DEV_DATASET=nvme2n1
# Directory with queries used to run Lucene workloads
#QUERIES_DIR=${BENCH_DIR}/lucene/scripts/queries
QUERIES_DIR=/archive/users/kolokasis/lucene/queries/real_dataset_queries
# Device for H2
DEV_H2=nvme1n1
# Mount point for H2 TeraHeap directory
MNT_H2=/mnt/fmap
# Card segment size for H2
CARD_SIZE=$((8 * 1024))
# Region size for H2
REGION_SIZE=$((256 * 1024 * 1024))
# Stripe size for H2
STRIPE_SIZE=$(( REGION_SIZE / CARD_SIZE ))
# TeraCache file size in GB e.g 800 -> 800GB
H2_FILE_SZ=800
#Benchmark log
BENCH_LOG=${BENCH_DIR}/lucene/scripts/log.out

# ----------------------

