- name: purge unneeded dependencies
  apt:
    purge: yes
    autoremove: yes

- name: clean up unneeded cached packages
  apt:
    autoclean: yes

- name: reset apt to a useful state
  apt:
    update_cache: yes
