---
- name: Check for Anaconda
  stat:
    path: "{{ anaconda_home }}"
  register: anaconda_dir

- block:
  - name: Download Anaconda
    get_url:
      url: "{{ anaconda_installer }}"
      dest: /tmp/{{ anaconda_version }}

  - name: Install Anaconda
    command: "bash /tmp/{{ anaconda_version }} -b -p {{ anaconda_home }}"
    become: yes
    become_user: jenkins

  - name: add anaconda bin to jenkins PATH in bashrc
    lineinfile:
      name: /home/jenkins/.bashrc
      state: present
      insertafter: EOF
      line: "export PATH=/home/jenkins/anaconda2/bin:$PATH"

  - name: delete Anaconda download
    file:
      path: "/tmp/{{ anaconda_version }}"
      state: absent
  when: anaconda_dir.stat.islnk is not defined

- name: check for py3 env
  command: "conda env list"
  environment:
    PATH: "{{ anaconda_home }}/bin:{{ ansible_env.PATH }}"
  changed_when: False
  check_mode: no
  register: py3_check

- block:
  - name: Create Python Env
    command: "{{ anaconda_home }}/bin/conda create -y --name py3 python=3.6"
    become: yes
    become_user: jenkins
  when: "'py3' not in py3_check.stdout"

- name: update anaconda pip for py2.7
  command: "{{ anaconda_home }}/bin/pip install --upgrade pip"
  become: yes
  become_user: jenkins
  tags:
    - skip_ansible_lint

- name: update anaconda pip for py3
  command: "{{ anaconda_home }}/envs/py3/bin/pip install --upgrade pip"
  become: yes
  become_user: jenkins
  tags:
    - skip_ansible_lint

- name: copy pip requirments for py3
  copy:
    src: "python_environments/{{ anaconda_py3_pip_requirements }}"
    dest: "/tmp/{{ anaconda_py3_pip_requirements }}"
    owner: jenkins
    group: jenkins
    mode: 0660

- name: install py3 pip packages
  pip:
    requirements: "/tmp/{{ anaconda_py3_pip_requirements }}"
  environment:
    PATH: "{{ anaconda_home }}/envs/py3/bin:{{ ansible_env.PATH }}"
  become: yes
  become_user: jenkins

- name: delete py3 pip requirements file
  file:
    path: "/tmp/{{ anaconda_py3_pip_requirements }}"
    state: absent
