---
# install minikube
- name: download kubectl binary
  get_url:
    url: '{{ kubectl_url }}'
    dest: '{{ kubectl_install_dir }}/{{ kubectl_target }}'
    mode: 0755

- name: install minikube
  apt:
    deb: '{{ minikube_url }}'

- name: set k8s version
  command: "/usr/bin/minikube config set kubernetes-version {{ k8s_version }}"
  become: yes
  become_user: jenkins
