---
# set up the required system packages for a host
- name: install base build/compilation tools
  apt:
    pkg:
      - autoconf
      - maven
      - gcc
      - make
      - cmake
      - g++
      - libssl-dev
      - libev-dev
      - libevent-dev
      - libffi-dev
      - curl
      - python-dev
      - clang-format
      - pkg-config
    state: present
    update_cache: yes
