---
# set up and install docker
- name: docker repo signing key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: docker repo
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'
    state: present
    update_cache: yes
    filename: docker

- name: install docker-ce and docker-compose
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    state: present
    update_cache: yes

- name: enable docker service
  service:
    name: docker
    enabled: yes

- name: put jenkins in docker group
  user:
    name: jenkins
    groups: docker
