---
# set up the jenkins user first, before anything is installed and set up
- name: set up the jenkins environment
  include: jenkins_userspace.yml

- name: install system packages for software builds
  include: install_build_packages.yml

- name: install docker
  include: install_docker.yml

- name: install minikube
  include: install_minikube.yml

- name: install anaconda and associated packages
  include: install_anaconda.yml

- name: install spark build packages
  include: install_spark_build_packages.yml

- name: clean up apt
  include: cleanup.yml
