#!/usr/bin/env bash

JAVA_HOME=/spare/perpap/openjdk/aarch64/jdk-17.0.10+7
SPARK_WORKER_CORES=160
SPARK_WORKER_INSTANCES=1
SPARK_WORKER_MEMORY=12000g
SPARK_WORKER_MEMORY=12000g
SPARK_LOCAL_DIRS=/mnt/fmap
SPARK_MASTER_IP=spark://ampere:7077
SPARK_MASTER_HOST=ampere
SPARK_LOCAL_IP=ampere
